### ISSUE TITLE
Command line + Attached windows(cygwin executable)

### ISSUE THREAD

**Issue by SnoopyTools** [hyc/a9serv#4]
Could you provide a brief explanation of the -b, -l, and -p command line options and IP address please. Does this output to browser window through http://xxx.xxx.xxx.x.x:3000 or whatever like the node js version? is the supplied ip address the output or the input address? thanks

Also attached windows (cygwin) executable for anyone that wants it 

[A9camPPPP.zip](https://github.com/user-attachments/files/18270651/A9camPPPP.zip)

**Comment by hyc** [comment]
-b sets the broadcast address of the local network, which is used to find the camera's address. If you know the camera's address already you can use that here instead of a network broadcast address.

-l sets the address for the program itself to listen on. You only need this if you have multiple network interfaces and you only want to listen on a single specific one, otherwise this option is unneeded.

-p sets the port that the program will listen on.
